version: "3.3"

services:

  front-vega-rb:
    build:
      context: ./docker
      dockerfile: Dockerfile-app-yc
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
    volumes:
      - ./:/usr/src/app

  front-vega-rb-nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx-yc
      args:
        BACKEND_API: http://vega_back:8080
    volumes:
      - ./build:/opt/app-root/www/
    environment:
      - VIRTUAL_HOST=vega-rb.ne.vegaspace.tk
      - LETSENCRYPT_HOST=vega-rb.ne.vegaspace.tk
      - VIRTUAL_PORT=80
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
